// hvm_example.c - HOSC Virtual Machine Example
//
// Demonstrates how to use the HOSC Virtual Machine (HVM) to execute
// bytecode compiled from HOSC language source code.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "hvm.h"
#include "hvm_compiler.h"
#include "ast.h"
#include "parser.h"

// Example: Compile and execute a simple HOSC program
int main() {
    printf("=== HOSC Virtual Machine (HVM) Demo ===\n\n");
    
    // Create HVM instance
    HVM_VM* vm = hvm_create();
    if (!vm) {
        printf("Error: Failed to create HVM instance\n");
        return 1;
    }
    
    // Create compiler
    HVM_Compiler* compiler = hvm_compiler_create(vm);
    if (!compiler) {
        printf("Error: Failed to create HVM compiler\n");
        hvm_destroy(vm);
        return 1;
    }
    
    // Example HOSC source code
    const char* hosc_source = "let x = 42; let y = 3.14; print \"Hello, HVM!\";";
    
    printf("HOSC Source: %s\n\n", hosc_source);
    
    // Parse HOSC source into AST
    ASTNode* ast = parser_parse(hosc_source);
    if (!ast) {
        printf("Error: Failed to parse HOSC source\n");
        hvm_compiler_destroy(compiler);
        hvm_destroy(vm);
        return 1;
    }
    
    printf("AST parsed successfully!\n");
    
    // Compile AST to bytecode
    if (!hvm_compiler_compile_ast(compiler, ast)) {
        printf("Error: Failed to compile AST to bytecode\n");
        if (hvm_compiler_has_errors(compiler)) {
            hvm_compiler_print_errors(compiler);
        }
        ast_destroy(ast);
    hvm_compiler_destroy(compiler);
        hvm_destroy(vm);
        return 1;
    }
    
    printf("AST compiled to bytecode successfully!\n\n");
    
    // Print generated bytecode
    printf("Generated Bytecode:\n");
    hvm_print_instructions(vm);
    printf("\n");
    
    // Execute bytecode
    printf("Executing bytecode...\n");
    printf("Output:\n");
    if (!hvm_run(vm)) {
        printf("Error: Failed to execute bytecode\n");
        const char* error = hvm_get_error(vm);
        if (error) {
            printf("VM Error: %s\n", error);
        }
    }
    
    printf("\nExecution completed!\n");
    
    // Print final stack state
    printf("\nFinal Stack State:\n");
    hvm_print_stack(vm);
    
    // Cleanup
    ast_destroy(ast);
    hvm_compiler_destroy(compiler);
    hvm_destroy(vm);
    
    return 0;
}


