/*
 * HOSC Bootstrap — Native Command: make_window
 * File: bootstrap/src/commands/make_window.c
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#define _POSIX_C_SOURCE 200809L
#include "commands/make_window.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ─────────────────────────────────────────────────────────────────────────
 * bs_native_make_window
 *
 * Called from HOSC when the user writes:
 *
 *     make_window(title width height);
 *
 * Parameters received via `args` array (count = 3):
    //   args[0] — title
    //   args[1] — width
    //   args[2] — height
 * Return a BsValue (use bs_null(), bs_int(), bs_string(), etc.)
 * ───────────────────────────────────────────────────────────────────────── */
BsValue bs_native_make_window(BsRuntime *runtime, BsValue *args, size_t argc) {
    (void)runtime;

    if (argc < 3) {
        fprintf(stderr, "[make_window] expected 3 arg(s), got %zu\n", argc);
        return bs_null();
    }

    // BsValue title_val = args[0]; // index 0
    // BsValue width_val = args[1]; // index 1
    // BsValue height_val = args[2]; // index 2
    /* ── TODO: implement make_window logic here ─────────────────────────── */
    printf("[make_window] called");
    if (argc > 0) { printf(", title="); bs_print_value(args[0]); }
    if (argc > 1) { printf(", width="); bs_print_value(args[1]); }
    if (argc > 2) { printf(", height="); bs_print_value(args[2]); }
    printf("\n");
    /* ─────────────────────────────────────────────────────────────────────── */

    return bs_null();
}

/* Register this command into a BsRuntime */
void make_window_register(BsRuntime *runtime) {
    bootstrap_register_command(runtime, "make_window", 3, bs_native_make_window);
}
