/*
 * HOSC Bootstrap — Native Command: play_sound
 * File: bootstrap/src/commands/play_sound.c
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#define _POSIX_C_SOURCE 200809L
#include "commands/play_sound.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ─────────────────────────────────────────────────────────────────────────
 * bs_native_play_sound
 *
 * Called from HOSC when the user writes:
 *
 *     play_sound(filepath volume);
 *
 * Parameters received via `args` array (count = 2):
    //   args[0] — filepath
    //   args[1] — volume
 * Return a BsValue (use bs_null(), bs_int(), bs_string(), etc.)
 * ───────────────────────────────────────────────────────────────────────── */
BsValue bs_native_play_sound(BsRuntime *runtime, BsValue *args, size_t argc) {
    (void)runtime;

    if (argc < 2) {
        fprintf(stderr, "[play_sound] expected 2 arg(s), got %zu\n", argc);
        return bs_null();
    }

    // BsValue filepath_val = args[0]; // index 0
    // BsValue volume_val = args[1]; // index 1
    /* ── TODO: implement play_sound logic here ─────────────────────────── */
    printf("[play_sound] called");
    if (argc > 0) { printf(", filepath="); bs_print_value(args[0]); }
    if (argc > 1) { printf(", volume="); bs_print_value(args[1]); }
    printf("\n");
    /* ─────────────────────────────────────────────────────────────────────── */

    return bs_null();
}

/* Register this command into a BsRuntime */
void play_sound_register(BsRuntime *runtime) {
    bootstrap_register_command(runtime, "play_sound", 2, bs_native_play_sound);
}
