/*
 * HOSC Bootstrap — Native Command: send_packet
 * File: bootstrap/src/commands/send_packet.c
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#define _POSIX_C_SOURCE 200809L
#include "commands/send_packet.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ─────────────────────────────────────────────────────────────────────────
 * bs_native_send_packet
 *
 * Called from HOSC when the user writes:
 *
 *     send_packet(host, port, payload);
 *
 * Parameters received via `args` array (count = 3):
    //   args[0] — host
    //   args[1] — port
    //   args[2] — payload
 * Return a BsValue (use bs_null(), bs_int(), bs_string(), etc.)
 * ───────────────────────────────────────────────────────────────────────── */
BsValue bs_native_send_packet(BsRuntime *runtime, BsValue *args, size_t argc) {
    (void)runtime;

    if (argc < 3) {
        fprintf(stderr, "[send_packet] expected 3 arg(s), got %zu\n", argc);
        return bs_null();
    }

    // BsValue host_val = args[0]; // index 0
    // BsValue port_val = args[1]; // index 1
    // BsValue payload_val = args[2]; // index 2
    /* ── TODO: implement send_packet logic here ─────────────────────────── */
    printf("[send_packet] called");
    if (argc > 0) { printf(", host="); bs_print_value(args[0]); }
    if (argc > 1) { printf(", port="); bs_print_value(args[1]); }
    if (argc > 2) { printf(", payload="); bs_print_value(args[2]); }
    printf("\n");
    /* ─────────────────────────────────────────────────────────────────────── */

    return bs_null();
}

/* Register this command into a BsRuntime */
void send_packet_register(BsRuntime *runtime) {
    bootstrap_register_command(runtime, "send_packet", 3, bs_native_send_packet);
}
