/*
 * HOSC Bootstrap — Native Command: draw_rect
 * File: bootstrap/include/commands/draw_rect.h
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#ifndef HOSC_BS_CMD_DRAW_RECT_H
#define HOSC_BS_CMD_DRAW_RECT_H

#include "bs_value.h"
#include "bs_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * bs_native_draw_rect
 *   HOSC name    : draw_rect
 *   Param count  : 5
    //   args[0] — x
    //   args[1] — y
    //   args[2] — width
    //   args[3] — height
    //   args[4] — color */
BsValue bs_native_draw_rect(BsRuntime *runtime, BsValue *args, size_t argc);

/* Convenience: register this command into a runtime */
void draw_rect_register(BsRuntime *runtime);

#ifdef __cplusplus
}
#endif

#endif /* HOSC_BS_CMD_DRAW_RECT_H */
