/*
 * HOSC Bootstrap — Native Command: make_window
 * File: bootstrap/include/commands/make_window.h
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#ifndef HOSC_BS_CMD_MAKE_WINDOW_H
#define HOSC_BS_CMD_MAKE_WINDOW_H

#include "bs_value.h"
#include "bs_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * bs_native_make_window
 *   HOSC name    : make_window
 *   Param count  : 3
    //   args[0] — title
    //   args[1] — width
    //   args[2] — height */
BsValue bs_native_make_window(BsRuntime *runtime, BsValue *args, size_t argc);

/* Convenience: register this command into a runtime */
void make_window_register(BsRuntime *runtime);

#ifdef __cplusplus
}
#endif

#endif /* HOSC_BS_CMD_MAKE_WINDOW_H */
