/*
 * HOSC Bootstrap — Native Command: play_sound
 * File: bootstrap/include/commands/play_sound.h
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#ifndef HOSC_BS_CMD_PLAY_SOUND_H
#define HOSC_BS_CMD_PLAY_SOUND_H

#include "bs_value.h"
#include "bs_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * bs_native_play_sound
 *   HOSC name    : play_sound
 *   Param count  : 2
    //   args[0] — filepath
    //   args[1] — volume */
BsValue bs_native_play_sound(BsRuntime *runtime, BsValue *args, size_t argc);

/* Convenience: register this command into a runtime */
void play_sound_register(BsRuntime *runtime);

#ifdef __cplusplus
}
#endif

#endif /* HOSC_BS_CMD_PLAY_SOUND_H */
