/*
 * HOSC Bootstrap — Native Command: send_packet
 * File: bootstrap/include/commands/send_packet.h
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#ifndef HOSC_BS_CMD_SEND_PACKET_H
#define HOSC_BS_CMD_SEND_PACKET_H

#include "bs_value.h"
#include "bs_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * bs_native_send_packet
 *   HOSC name    : send_packet
 *   Param count  : 3
    //   args[0] — host
    //   args[1] — port
    //   args[2] — payload */
BsValue bs_native_send_packet(BsRuntime *runtime, BsValue *args, size_t argc);

/* Convenience: register this command into a runtime */
void send_packet_register(BsRuntime *runtime);

#ifdef __cplusplus
}
#endif

#endif /* HOSC_BS_CMD_SEND_PACKET_H */
