/* hosc_compiler.c - HOSC source file */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "parser.h"
#include "codegen.h"
#include "hvm.h"
#include "hvm_compiler.h"
#include "bytecode_io.h"
#include "file_utils.h"

static int write_c_file(const char *path, const char *code) {
    FILE *fp = fopen(path, "wb");
    if (!fp) return 0;
    fputs(code, fp);
    fclose(fp);
    return 1;
}

static int run_c_compiler(const char *c_path, const char *exe_path) {
    char command[1024];
    int written = snprintf(command, sizeof(command), "gcc -O2 -std=c99 \"%s\" -o \"%s\"", c_path, exe_path);
    if (written < 0 || written >= (int)sizeof(command)) return 0;
    return system(command) == 0;
}

static int compile_to_bytecode(ASTNode *ast, const char *bc_path, int run_after) {
    int ok = 0;
    HVM_VM *vm = hvm_create();
    HVM_Compiler *c = hvm_compiler_create(vm);
    if (!vm || !c) goto done;
    if (!hvm_compiler_compile_ast(c, ast)) goto done;
    if (bc_path) {
        if (!hvm_bytecode_write_file(vm->instructions, vm->instruction_count, bc_path)) goto done;
        printf("Generated bytecode: %s\n", bc_path);
    }
    if (run_after) {
        if (!hvm_run(vm)) {
            fprintf(stderr, "VM execution failed\n");
            goto done;
        }
    }
    ok = 1;

done:
    hvm_compiler_destroy(c);
    hvm_destroy(vm);
    return ok;
}

static void print_usage(const char *exe) {
    fprintf(stderr, "Usage:\n");
    fprintf(stderr, "  %s <input.hosc> [-c out.c] [-o out.exe] [-b out.hbc] [-r]\n", exe);
    fprintf(stderr, "Options:\n  -c  emit C source\n  -o  build native exe via gcc (needs gcc)\n  -b  emit bytecode file (.hbc)\n  -r  run with VM (no gcc needed)\n");
}

int main(int argc, char **argv) {
    const char *input_path;
    const char *c_output_path = NULL;
    const char *exe_output_path = NULL;
    const char *bc_output_path = NULL;
    int run_vm = 0;
    int i;

    if (argc < 2) { print_usage(argv[0]); return 1; }
    input_path = argv[1];

    for (i = 2; i < argc; i++) {
        if (strcmp(argv[i], "-c") == 0 && i + 1 < argc) {
            c_output_path = argv[++i];
        } else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            exe_output_path = argv[++i];
        } else if (strcmp(argv[i], "-b") == 0 && i + 1 < argc) {
            bc_output_path = argv[++i];
        } else if (strcmp(argv[i], "-r") == 0) {
            run_vm = 1;
        } else {
            print_usage(argv[0]);
            return 1;
        }
    }

    char *source = hosc_read_text_file(input_path, NULL);
    if (!source) { fprintf(stderr, "Error: cannot read %s\n", input_path); return 1; }

    ASTNode *ast = parser_parse(source);
    free(source);
    if (!ast) { fprintf(stderr, "Error: parse failed\n"); return 1; }

    if (bc_output_path || run_vm) {
        int ok = compile_to_bytecode(ast, bc_output_path, run_vm);
        ast_destroy(ast);
        return ok ? 0 : 1;
    }

    if (!c_output_path) c_output_path = "output.c";

    char *code = codegen_generate(ast);
    ast_destroy(ast);
    if (!code) { fprintf(stderr, "Error: codegen failed\n"); return 1; }

    if (!write_c_file(c_output_path, code)) {
        free(code);
        fprintf(stderr, "Error: cannot write %s\n", c_output_path);
        return 1;
    }
    printf("Generated C file: %s\n", c_output_path);

    if (exe_output_path) {
        if (!run_c_compiler(c_output_path, exe_output_path)) {
            free(code);
            fprintf(stderr, "Error: native compilation failed\n");
            return 1;
        }
        printf("Generated executable: %s\n", exe_output_path);
    }

    free(code);
    return 0;
}







