#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# add_command.sh — HOSC Bootstrap: Scaffold a new native C command
#
# Usage:
#   ./tools/add_command.sh <command_name> [param1 param2 ...]
#
# What it does:
#   1. Generates a C callback stub in  bootstrap/src/commands/<name>.c
#   2. Generates a header in           bootstrap/include/commands/<name>.h
#   3. Appends the registration call to bootstrap/src/bs_runtime.c  (builtins)
#   4. Appends #include and source to  bootstrap/CMakeLists.txt
#   5. Generates a .hosc usage example in bootstrap/examples/cmd_<name>.hosc
#
# Example:
#   ./tools/add_command.sh make_sound pitch volume
#   → registers `make_sound(pitch, volume)` so HOSC code can call it directly
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BS_SRC="$ROOT/bootstrap/src"
BS_INC="$ROOT/bootstrap/include"
BS_EX="$ROOT/bootstrap/examples"
BS_CMAKEFILE="$ROOT/bootstrap/CMakeLists.txt"
RUNTIME_C="$BS_SRC/bs_runtime.c"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[info]${RESET}  $*"; }
success() { echo -e "${GREEN}[done]${RESET}  $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
error()   { echo -e "${RED}[error]${RESET} $*" >&2; exit 1; }

# ── Argument validation ───────────────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
    echo -e "${BOLD}Usage:${RESET}  $0 <command_name> [param1 param2 ...]"
    echo ""
    echo "Examples:"
    echo "  $0 make_window title width height"
    echo "  $0 play_sound  filepath volume"
    echo "  $0 ping"
    exit 1
fi

CMD_NAME="$1"; shift
PARAMS=("$@")
PARAM_COUNT="${#PARAMS[@]}"

# Validate command name (identifier rules)
if ! [[ "$CMD_NAME" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
    error "Invalid command name '$CMD_NAME'. Must be a valid C identifier."
fi

# Guard: existing command?
CMD_C_FILE="$BS_SRC/commands/${CMD_NAME}.c"
CMD_H_FILE="$BS_INC/commands/${CMD_NAME}.h"
if [[ -f "$CMD_C_FILE" ]]; then
    warn "Command '$CMD_NAME' already exists at $CMD_C_FILE"
    read -r -p "Overwrite? [y/N] " yn
    [[ "$yn" =~ ^[yY] ]] || { info "Aborted."; exit 0; }
fi

# ── Derive C identifiers ──────────────────────────────────────────────────────
GUARD="${CMD_NAME^^}_H"                 # MAKE_WINDOW_H
FN_NAME="bs_native_${CMD_NAME}"         # bs_native_make_window

# ── Build param doc strings ───────────────────────────────────────────────────
param_doc=""
param_access=""
for i in "${!PARAMS[@]}"; do
    p="${PARAMS[$i]}"
    param_doc+="    //   args[$i] — $p\n"
    param_access+="    // BsValue ${p}_val = args[$i]; // index $i\n"
done
if [[ $PARAM_COUNT -eq 0 ]]; then
    param_doc="    // (no parameters)\n"
fi

# ── Param list for HOSC example ───────────────────────────────────────────────
hosc_params=""
hosc_call_args=""
if [[ $PARAM_COUNT -gt 0 ]]; then
    for i in "${!PARAMS[@]}"; do
        p="${PARAMS[$i]}"
        if [[ $i -gt 0 ]]; then
            hosc_params+=", "
            hosc_call_args+=", "
        fi
        hosc_params+="$p"
        hosc_call_args+="\"<${p}>\""
    done
fi

# ── Create output directories ─────────────────────────────────────────────────
mkdir -p "$BS_SRC/commands"
mkdir -p "$BS_INC/commands"

# ═════════════════════════════════════════════════════════════════════════════
# 1. Header file
# ═════════════════════════════════════════════════════════════════════════════
cat > "$CMD_H_FILE" << HEADER
/*
 * HOSC Bootstrap — Native Command: ${CMD_NAME}
 * File: bootstrap/include/commands/${CMD_NAME}.h
 * Auto-generated by tools/add_command.sh — edit freely.
 */

#ifndef HOSC_BS_CMD_${GUARD}
#define HOSC_BS_CMD_${GUARD}

#include "bs_value.h"
#include "bs_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * ${FN_NAME}
 *   HOSC name    : ${CMD_NAME}
 *   Param count  : ${PARAM_COUNT}
$(printf "%b" "$param_doc") */
BsValue ${FN_NAME}(BsRuntime *runtime, BsValue *args, size_t argc);

/* Convenience: register this command into a runtime */
void ${CMD_NAME}_register(BsRuntime *runtime);

#ifdef __cplusplus
}
#endif

#endif /* HOSC_BS_CMD_${GUARD} */
HEADER

success "Header    → bootstrap/include/commands/${CMD_NAME}.h"

# ═════════════════════════════════════════════════════════════════════════════
# 2. Implementation file — type-aware stub
# ═════════════════════════════════════════════════════════════════════════════

# Build per-param type-check + access code
param_type_checks=""
param_bindings=""
param_printf_fmt=""
param_printf_args=""
for i in "${!PARAMS[@]}"; do
    p="${PARAMS[$i]}"
    param_type_checks+="    /* args[$i] = ${p} : check type before use */\n"
    param_type_checks+="    // if (args[$i].type != BS_VAL_INT) { /* handle type error */ }\n"
    param_bindings+="    BsValue ${p}_val = args[$i];\n"
    param_bindings+="    // int64_t   ${p} = ${p}_val.as.integer;       // if INT\n"
    param_bindings+="    // double    ${p} = ${p}_val.as.floating;      // if FLOAT\n"
    param_bindings+="    // char     *${p} = ${p}_val.as.string;        // if STRING\n"
    param_bindings+="    // bool      ${p} = ${p}_val.as.boolean;       // if BOOL\n"
    if [[ $i -gt 0 ]]; then
        param_printf_fmt+=", "
        param_printf_args+=", "
    fi
    param_printf_fmt+="${p}="
    param_printf_args+="args[$i].type==BS_VAL_INT ? (void)0 : (void)0"
done
[[ $PARAM_COUNT -eq 0 ]] && param_bindings="    /* no parameters */\n"

# Build the debug print loop body separately (avoids heredoc var issues)
PRINT_LINES=""
for i in "${!PARAMS[@]}"; do
    p="${PARAMS[$i]}"
    PRINT_LINES+="    if (argc > ${i}) { printf(\", ${p}=\"); bs_print_value(args[${i}]); }\n"
done

cat > "$CMD_C_FILE" << IMPL
/*
 * HOSC Bootstrap — Native Command: ${CMD_NAME}
 * File: bootstrap/src/commands/${CMD_NAME}.c
 * Auto-generated by tools/add_command.sh — edit freely.
 *
 * BsValue type access reference:
 *   args[i].type                     — BS_VAL_NULL | BS_VAL_BOOL | BS_VAL_INT
 *                                       BS_VAL_FLOAT | BS_VAL_STRING | BS_VAL_FUNCTION
 *   args[i].as.integer  (int64_t)    — when type == BS_VAL_INT
 *   args[i].as.floating (double)     — when type == BS_VAL_FLOAT
 *   args[i].as.string   (char*)      — when type == BS_VAL_STRING
 *   args[i].as.boolean  (bool)       — when type == BS_VAL_BOOL
 */

#define _POSIX_C_SOURCE 200809L
#include "commands/${CMD_NAME}.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ─────────────────────────────────────────────────────────────────────────
 * ${FN_NAME}
 *
 * HOSC call site:
 *   ${CMD_NAME}(${hosc_params});
 *
 * Parameters (${PARAM_COUNT}):
$(printf "%b" "$param_doc")
 * Returns: BsValue — use bs_null(), bs_bool(), bs_int(), bs_float(), bs_string()
 * ───────────────────────────────────────────────────────────────────────── */
BsValue ${FN_NAME}(BsRuntime *runtime, BsValue *args, size_t argc) {
    (void)runtime;

    /* ── Arity guard ────────────────────────────────────────────────────── */
    if (argc < ${PARAM_COUNT}) {
        fprintf(stderr, "[${CMD_NAME}] expected ${PARAM_COUNT} arg(s), got %zu\\n", argc);
        return bs_null();
    }

    /* ── Typed argument bindings ────────────────────────────────────────── */
    /*
     * IMPORTANT: always check args[i].type before accessing the union.
     * Accessing .as.integer on a BS_VAL_STRING is undefined behaviour.
     *
     * Example (typed):
     *   if (args[0].type != BS_VAL_INT) {
     *       fprintf(stderr, "[${CMD_NAME}] arg 0 must be INT\\n");
     *       return bs_null();
     *   }
     *   int64_t x = args[0].as.integer;
     */
$(printf "%b" "$param_bindings")
    /* ── TODO: implement ${CMD_NAME} logic here ─────────────────────────── */
    printf("[${CMD_NAME}] called");
IMPL

printf "%b" "$PRINT_LINES" >> "$CMD_C_FILE"

cat >> "$CMD_C_FILE" << IMPL_END
    printf("\\n");
    /* ─────────────────────────────────────────────────────────────────────── */

    return bs_null(); /* TODO: return meaningful value if needed */
}

/* Register this command into a BsRuntime */
void ${CMD_NAME}_register(BsRuntime *runtime) {
    bootstrap_register_command(runtime, "${CMD_NAME}", ${PARAM_COUNT}, ${FN_NAME});
}
IMPL_END


success "Source    → bootstrap/src/commands/${CMD_NAME}.c"

# ═════════════════════════════════════════════════════════════════════════════
# 3. Append registration to bs_runtime.c
# ═════════════════════════════════════════════════════════════════════════════
if grep -q "\"${CMD_NAME}\"" "$RUNTIME_C" 2>/dev/null; then
    warn "Registration for '${CMD_NAME}' already in bs_runtime.c — skipping."
else
    INCLUDE_LINE="#include \"commands/${CMD_NAME}.h\""
    # Add #include after last existing #include in file
    python3 - <<PY
import re
path = "${RUNTIME_C}"
src  = open(path).read()
inc  = '${INCLUDE_LINE}'
last = list(re.finditer(r'^#include\s+[<"].*?[>"]', src, re.MULTILINE))
if last and inc not in src:
    pos = last[-1].end()
    src = src[:pos] + '\n' + inc + src[pos:]
    open(path,'w').write(src)
PY

    # Inject registration call into bs_runtime_register_builtins body
    python3 - <<PY
path = "${RUNTIME_C}"
src  = open(path).read()
call = '    ${CMD_NAME}_register(runtime);\n'
fn   = 'void bs_runtime_register_builtins(BsRuntime *runtime) {'
if call not in src and fn in src:
    idx   = src.index(fn) + len(fn)
    depth = 1; i = idx
    while i < len(src) and depth > 0:
        if src[i] == '{': depth += 1
        elif src[i] == '}': depth -= 1
        i += 1
    src = src[:i-1] + call + src[i-1:]
    open(path,'w').write(src)
PY
    success "Registered → bs_runtime_register_builtins() in bs_runtime.c"
fi

# ═════════════════════════════════════════════════════════════════════════════
# 4. Add source file to CMakeLists.txt
# ═════════════════════════════════════════════════════════════════════════════
CMAKE_ENTRY="    src/commands/${CMD_NAME}.c"
if grep -qF "$CMAKE_ENTRY" "$BS_CMAKEFILE"; then
    warn "CMakeLists.txt already contains the entry — skipping."
else
    python3 - <<PY
path  = "${BS_CMAKEFILE}"
entry = "    src/commands/${CMD_NAME}.c\n"
src   = open(path).read()
idx   = src.index("add_library(hosc_bootstrap STATIC")
end   = src.index("\n)", idx)
if entry not in src:
    src = src[:end] + "\n" + entry.rstrip() + src[end:]
    open(path,'w').write(src)
PY
    success "CMakeLists → added src/commands/${CMD_NAME}.c to hosc_bootstrap"
fi

# ═════════════════════════════════════════════════════════════════════════════
# 5. Generate .hosc usage example
# ═════════════════════════════════════════════════════════════════════════════
EXAMPLE_FILE="$BS_EX/cmd_${CMD_NAME}.hosc"

if [[ $PARAM_COUNT -eq 0 ]]; then
    hosc_call="${CMD_NAME}();"
else
    hosc_call="${CMD_NAME}(${hosc_call_args});"
fi

param_comment=""
for i in "${!PARAMS[@]}"; do
    param_comment+="//   arg $((i+1)): ${PARAMS[$i]}\n"
done
if [[ $PARAM_COUNT -eq 0 ]]; then
    param_comment="//   (no parameters)\n"
fi

# Build the wrapper call — use param names, not hard-coded strings
wrapper_call="${CMD_NAME}("
for i in "${!PARAMS[@]}"; do
    [[ $i -gt 0 ]] && wrapper_call+=", "
    wrapper_call+="${PARAMS[$i]}"
done
wrapper_call+=");"

cat > "$EXAMPLE_FILE" << EXAMPLE
// HOSC Bootstrap — Usage example for command: ${CMD_NAME}
// Auto-generated by tools/add_command.sh
//
// Parameters (${PARAM_COUNT}):
$(printf "%b" "$param_comment")
// Run:
//   ./build/bin/Debug/hosc-bootstrap run bootstrap/examples/cmd_${CMD_NAME}.hosc

package main

// AST command wrapper — forwards all params to the native C implementation
command use_${CMD_NAME}(${hosc_params}) {
    ${CMD_NAME}(${hosc_params});
    print("${CMD_NAME}: done.");
}

func main() {
    print("=== ${CMD_NAME} demo ===");

    // Direct native C dispatch through CommandRegistry:
    ${hosc_call}

    // Via AST command wrapper:
    use_${CMD_NAME}(${hosc_call_args});

    print("=== done ===");
}
EXAMPLE

success "Example   → bootstrap/examples/cmd_${CMD_NAME}.hosc"

# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}┌──────────────────────────────────────────────────────────────┐${RESET}"
echo -e "${BOLD}│  Command '${CMD_NAME}' scaffolded successfully                ${RESET}"
echo -e "${BOLD}└──────────────────────────────────────────────────────────────┘${RESET}"
echo ""
echo -e "  ${CYAN}Files created / modified:${RESET}"
echo -e "    ${GREEN}+${RESET}  bootstrap/include/commands/${CMD_NAME}.h"
echo -e "    ${GREEN}+${RESET}  bootstrap/src/commands/${CMD_NAME}.c"
echo -e "    ${YELLOW}~${RESET}  bootstrap/src/bs_runtime.c      (registration injected)"
echo -e "    ${YELLOW}~${RESET}  bootstrap/CMakeLists.txt         (source entry added)"
echo -e "    ${GREEN}+${RESET}  bootstrap/examples/cmd_${CMD_NAME}.hosc"
echo ""
echo -e "  ${CYAN}Next steps:${RESET}"
echo -e "  ${BOLD}1.${RESET} Implement the logic:"
echo -e "       \$EDITOR bootstrap/src/commands/${CMD_NAME}.c"
echo ""
echo -e "  ${BOLD}2.${RESET} Rebuild:"
echo -e "       cmake --build build --target hosc-bootstrap"
echo ""
echo -e "  ${BOLD}3.${RESET} Run the generated example:"
echo -e "       ./build/bin/Debug/hosc-bootstrap run bootstrap/examples/cmd_${CMD_NAME}.hosc"
echo ""
